### ISSUE TITLE
`require': cannot load such file -- gda/gda (LoadError) since v1.1.2

### ISSUE THREAD

**Issue by sue445** [tenderlove/gda#7]
Since gda gem v1.1.2, I get an error just to `require`

# My code
```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "gda", "1.1.2"
end

require "gda"
```

# Expected
No error.

# Actual
```bash
$ ruby temp.rb
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.3.7
Using gda 1.1.2
/Users/sue445/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/gda-1.1.2/lib/gda.rb:1:in `require': cannot load such file -- gda/gda (LoadError)
	from /Users/sue445/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/gda-1.1.2/lib/gda.rb:1:in `<top (required)>'
	from /Users/sue445/.rbenv/versions/3.1.1/lib/ruby/3.1.0/bundler/runtime.rb:60:in `require'
	from /Users/sue445/.rbenv/versions/3.1.1/lib/ruby/3.1.0/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/sue445/.rbenv/versions/3.1.1/lib/ruby/3.1.0/bundler/runtime.rb:55:in `each'
	from /Users/sue445/.rbenv/versions/3.1.1/lib/ruby/3.1.0/bundler/runtime.rb:55:in `block in require'
	from /Users/sue445/.rbenv/versions/3.1.1/lib/ruby/3.1.0/bundler/runtime.rb:44:in `each'
	from /Users/sue445/.rbenv/versions/3.1.1/lib/ruby/3.1.0/bundler/runtime.rb:44:in `require'
	from /Users/sue445/.rbenv/versions/3.1.1/lib/ruby/3.1.0/bundler/inline.rb:71:in `block in gemfile'
	from /Users/sue445/.rbenv/versions/3.1.1/lib/ruby/3.1.0/bundler/settings.rb:131:in `temporary'
	from /Users/sue445/.rbenv/versions/3.1.1/lib/ruby/3.1.0/bundler/inline.rb:55:in `gemfile'
	from temp.rb:3:in `<main>'
```

Prior to v1.1.1 there was no problem

**Comment by tenderlove** [comment]
This should be fixed in 1.1.3.  Thanks for reporting this!
